### ISSUE TITLE
Add support for top-level documentation comments

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/codedoc#10]
From issue #9:

> Also I don't want to open another issue for this, but it would be nice if there was a way to put a comment at the beginning of a file and have it be top-level documentation.

**Comment by ghost** [comment]
Look at --body
```
codedoc foo.c --body  text.md >foo.html
```

**Comment by michaelrsweet** [comment]
Certainly the `--body` option is useful for incorporating arbitrary body text. However, this issue is tracking a potential future enhancement where the body text could be incorporated in source files, e.g.:

```
/*[codedoc-body

... markdown to include as body text for this portion of the source code ...

]*/
```

I'd like to review what HeaderDoc and other documentation generators do here, but in theory it could put all of the documentation in the source code, which could then be extracted for the separate man pages and combined HTML/EPUB output. Keeping the order of the sections would be important as the markdown would be embedded in the XML file as well...

**Comment by michaelrsweet** [comment]
[master 58fe8e5] Add support for @body@ comment directive (Issue #10)
