### ISSUE TITLE
Support simple markdown in comments

### ISSUE THREAD

**Issue by a-kramer** [michaelrsweet/codedoc#6]
Hello,
 is there a way to write an indented multiline code block in a function description?
`@code [...]@` does not allow line breaks in it and a possible workaround with multiple code snippets is not formatted right.

**Comment by michaelrsweet** [comment]
Sorry, not at present. I might be able to add support for markdown-style code fences (codedoc already supports backticks in place of `@code ...@`) so you can have something like:

```
/*
 * Some text leading up to an example:
 *
 * ```
 * if (foo)
 * {
 *    bar = 42;
 * }
 * ```
 */
```

**Comment by michaelrsweet** [comment]
OK, I'm going to add some simple markdown support beyond the current (undocumented) backtick code style:

- [x] Code fences with `\`\`\`\`
- [x] Bulleted lists with `- ` prefixes
- [x] Inline markup for `*italic*`, and `**bold**`.
- [x] Simple links like `[title]`, `[title](URL)`, and `<URL>`

**Comment by michaelrsweet** [comment]
[master 4fc229b] Implement emphasized text, code fences, and bullet lists (Issue #6)

**Comment by michaelrsweet** [comment]
[master 5c36e34] Add support for links in comments (Issue #6)

**Comment by a-kramer** [comment]
Oh, thank you very much, amazing!
