### ISSUE TITLE
namespace => no documentation generation.

### ISSUE THREAD

**Issue by ArthurSonzogni** [michaelrsweet/codedoc#7]
Hi,
I observed this code do not generate any documentation:

~~~cpp
namespace {
// My comment
void theFunction()
}
~~~

but this one does:

~~~cpp
// My comment
void theFunction()
~~~

I think codedoc do not handle C++ namespace properly.

**Comment by michaelrsweet** [comment]
Correct, right now the schema for the XML produced by codedoc supports namespaces but the code parser currently does not... Tracking for a future update...

**Comment by ArthurSonzogni** [comment]
Thanks!
CodeDoc is exactly the tool I am looking for. Thanks for the snap package ;-)

**Comment by michaelrsweet** [comment]
[master 5fd7dfc] Add support for C++ namespaces (Issue #7)
